@YourDebits_HostAddress = http://localhost:5002
@ApiKey = EE2620F94E704A9FB750D90F874DD859

### Listar débitos de um veículo (com débitos)
GET {{YourDebits_HostAddress}}/api/vehicle/ABC1234/debts
Authorization: {{ApiKey}}

###

### Listar débitos de um veículo (sem débitos)
GET {{YourDebits_HostAddress}}/api/vehicle/XYZ9999/debts
Authorization: {{ApiKey}}

###

### Sem Authorization (deve retornar 401)
GET {{YourDebits_HostAddress}}/api/vehicle/ABC1234/debts

###

### Toggle feature flag da API (habilita/desabilita a API)
POST {{YourDebits_HostAddress}}/api/feature-flag/toggle/api
Authorization: {{ApiKey}}

###

### Toggle feature flag de delay (habilita/desabilita o delay)
POST {{YourDebits_HostAddress}}/api/feature-flag/toggle/delay
Authorization: {{ApiKey}}

###

### Alterar tempo de delay (em ms)
PATCH {{YourDebits_HostAddress}}/api/feature-flag/delay?delayMs=2000
Authorization: {{ApiKey}}

###