@DebtsOnline_HostAddress = http://localhost:5127
@ApiKey = 37D016B8276D4ACB8F1813148A6422F8

### Listar débitos de um veículo (com débitos)
GET {{DebtsOnline_HostAddress}}/api/plate/ABC1234/debts
Authorization: {{ApiKey}}

###

### Listar débitos de um veículo (sem débitos)
GET {{DebtsOnline_HostAddress}}/api/plate/XYZ9999/debts
Authorization: {{ApiKey}}

###

### Sem Authorization (deve retornar 401)
GET {{DebtsOnline_HostAddress}}/api/plate/ABC1234/debts

###

### Toggle feature flag da API (habilita/desabilita a API)
POST {{DebtsOnline_HostAddress}}/api/feature-flag/toggle/api
Authorization: {{ApiKey}}

###

### Toggle feature flag de delay (habilita/desabilita o delay)
POST {{DebtsOnline_HostAddress}}/api/feature-flag/toggle/delay
Authorization: {{ApiKey}}

###

### Alterar tempo de delay (em ms)
PATCH {{DebtsOnline_HostAddress}}/api/feature-flag/delay?delayMs=2000
Authorization: {{ApiKey}}

###
